/**
 * The real topic vocabulary, generated from skkuverse-server.
 *
 * Source: `src/notices/categories.json` + `src/notices/sources.json`.
 * Regenerate rather than hand-edit — the keys are hash-locked upstream in
 * `.contracts.lock.json` ("notices.tab-keys") and CI fails on drift.
 *
 * Fixed tabs become `category:<key>`; picker tabs become `<pickerKey>:<id>`.
 * There is no rolled-up topic for a picker tab, which is why no selection can
 * reach every department subscriber — see TOPIC_LIMIT in the console.
 *
 * `adConsent` is false everywhere, and that is the true state rather than a
 * placeholder: a subscription records consent to a category of notice, not to
 * advertising. Until some topic genuinely carries marketing consent, the
 * console's advertising path correctly has no audience to offer.
 */
import type { Topic } from './types';

export const TOPICS: Topic[] = [
  { id: 'category:academic', label: { ko: '학사' }, group: '전체 공지', subscriberCount: 4595, adConsent: false },
  { id: 'category:scholarship', label: { ko: '장학' }, group: '전체 공지', subscriberCount: 1502, adConsent: false },
  { id: 'category:career', label: { ko: '취업' }, group: '전체 공지', subscriberCount: 3166, adConsent: false },
  { id: 'category:recruitment', label: { ko: '모집' }, group: '전체 공지', subscriberCount: 3104, adConsent: false },
  { id: 'category:event', label: { ko: '행사' }, group: '전체 공지', subscriberCount: 4846, adConsent: false },
  { id: 'dept:arch', label: { ko: '건축학과' }, group: '학과', subscriberCount: 549, adConsent: false },
  { id: 'dept:biz-undergrad', label: { ko: '경영대학(학부생)' }, group: '학과', subscriberCount: 824, adConsent: false },
  { id: 'dept:biz-grad', label: { ko: '경영대학(대학원)' }, group: '학과', subscriberCount: 299, adConsent: false },
  { id: 'dept:ecostat-undergrad', label: { ko: '경제대학(학부생)' }, group: '학과', subscriberCount: 37, adConsent: false },
  { id: 'dept:ecostat-grad', label: { ko: '경제대학(대학원)' }, group: '학과', subscriberCount: 374, adConsent: false },
  { id: 'dept:enc-undergrad', label: { ko: '공과대학(학부생)' }, group: '학과', subscriberCount: 571, adConsent: false },
  { id: 'dept:enc-grad', label: { ko: '공과대학(대학원)' }, group: '학과', subscriberCount: 759, adConsent: false },
  { id: 'dept:skku-edu-undergrad', label: { ko: '교육학과(학부생)' }, group: '학과', subscriberCount: 890, adConsent: false },
  { id: 'dept:skku-edu-grad', label: { ko: '교육학과(대학원)' }, group: '학과', subscriberCount: 303, adConsent: false },
  { id: 'dept:korean-undergrad', label: { ko: '국어국문학과(학부생)' }, group: '학과', subscriberCount: 717, adConsent: false },
  { id: 'dept:korean-grad', label: { ko: '국어국문학과(대학원)' }, group: '학과', subscriberCount: 463, adConsent: false },
  { id: 'dept:globalbiz', label: { ko: '글로벌경영학과' }, group: '학과', subscriberCount: 286, adConsent: false },
  { id: 'dept:globalecon', label: { ko: '글로벌경제학과' }, group: '학과', subscriberCount: 830, adConsent: false },
  { id: 'dept:gld', label: { ko: '글로벌리더학부' }, group: '학과', subscriberCount: 671, adConsent: false },
  { id: 'dept:gbme-undergrad', label: { ko: '글로벌바이오메디컬공학과(학부생)' }, group: '학과', subscriberCount: 508, adConsent: false },
  { id: 'dept:gbme-grad', label: { ko: '글로벌바이오메디컬공학과(대학원)' }, group: '학과', subscriberCount: 391, adConsent: false },
  { id: 'dept:sco', label: { ko: '글로벌융합학부(공통)' }, group: '학과', subscriberCount: 430, adConsent: false },
  { id: 'dept:sco-data', label: { ko: '글로벌융합학부(데이터사이언스융합전공)' }, group: '학과', subscriberCount: 518, adConsent: false },
  { id: 'dept:sco-info', label: { ko: '글로벌융합학부(인공지능융합전공)' }, group: '학과', subscriberCount: 476, adConsent: false },
  { id: 'dept:sco-magnetic', label: { ko: '글로벌융합학부(자기설계융합전공)' }, group: '학과', subscriberCount: 822, adConsent: false },
  { id: 'dept:sco-culture', label: { ko: '글로벌융합학부(컬처앤테크놀로지융합전공)' }, group: '학과', subscriberCount: 444, adConsent: false },
  { id: 'dept:mech-undergrad', label: { ko: '기계공학부(학부생)' }, group: '학과', subscriberCount: 402, adConsent: false },
  { id: 'dept:mech-grad', label: { ko: '기계공학부(대학원)' }, group: '학과', subscriberCount: 429, adConsent: false },
  { id: 'dept:german', label: { ko: '독어독문학과' }, group: '학과', subscriberCount: 754, adConsent: false },
  { id: 'dept:design-undergrad', label: { ko: '디자인학과(학부생)' }, group: '학과', subscriberCount: 715, adConsent: false },
  { id: 'dept:design-grad', label: { ko: '디자인학과(대학원)' }, group: '학과', subscriberCount: 788, adConsent: false },
  { id: 'dept:russian', label: { ko: '러시아어문학과' }, group: '학과', subscriberCount: 659, adConsent: false },
  { id: 'dept:dance', label: { ko: '무용학과' }, group: '학과', subscriberCount: 822, adConsent: false },
  { id: 'dept:liberalarts-undergrad', label: { ko: '문과대학(학부생)' }, group: '학과', subscriberCount: 93, adConsent: false },
  { id: 'dept:liberalarts-grad', label: { ko: '문과대학(대학원)' }, group: '학과', subscriberCount: 111, adConsent: false },
  { id: 'dept:lis-undergrad', label: { ko: '문헌정보학과(학부생)' }, group: '학과', subscriberCount: 465, adConsent: false },
  { id: 'dept:lis-grad', label: { ko: '문헌정보학과(대학원)' }, group: '학과', subscriberCount: 583, adConsent: false },
  { id: 'dept:physics', label: { ko: '물리학과' }, group: '학과', subscriberCount: 118, adConsent: false },
  { id: 'dept:mediacomm-undergrad', label: { ko: '미디어커뮤니케이션학과(학부생)' }, group: '학과', subscriberCount: 881, adConsent: false },
  { id: 'dept:mediacomm-grad', label: { ko: '미디어커뮤니케이션학과(대학원)' }, group: '학과', subscriberCount: 422, adConsent: false },
  { id: 'dept:biomecha', label: { ko: '바이오메카트로닉스학과' }, group: '학과', subscriberCount: 99, adConsent: false },
  { id: 'dept:sls-general', label: { ko: '법학과(일반대학원)' }, group: '학과', subscriberCount: 291, adConsent: false },
  { id: 'dept:sls-special', label: { ko: '법학전문대학원' }, group: '학과', subscriberCount: 81, adConsent: false },
  { id: 'dept:coe-undergrad', label: { ko: '사범대학(학부생)' }, group: '학과', subscriberCount: 391, adConsent: false },
  { id: 'dept:coe-grad', label: { ko: '사범대학(대학원)' }, group: '학과', subscriberCount: 428, adConsent: false },
  { id: 'dept:history-undergrad', label: { ko: '사학과(학부생)' }, group: '학과', subscriberCount: 250, adConsent: false },
  { id: 'dept:history-grad', label: { ko: '사학과(대학원)' }, group: '학과', subscriberCount: 403, adConsent: false },
  { id: 'dept:sscience-undergrad', label: { ko: '사회과학대학(학부생)' }, group: '학과', subscriberCount: 437, adConsent: false },
  { id: 'dept:sscience-grad', label: { ko: '사회과학대학(대학원)' }, group: '학과', subscriberCount: 763, adConsent: false },
  { id: 'dept:welfare', label: { ko: '사회복지학과' }, group: '학과', subscriberCount: 777, adConsent: false },
  { id: 'dept:soc', label: { ko: '사회학과' }, group: '학과', subscriberCount: 790, adConsent: false },
  { id: 'dept:biotech-undergrad', label: { ko: '생명공학대학(학부생)' }, group: '학과', subscriberCount: 421, adConsent: false },
  { id: 'dept:biotech-grad', label: { ko: '생명공학대학(대학원)' }, group: '학과', subscriberCount: 739, adConsent: false },
  { id: 'dept:ics', label: { ko: '성균융합원' }, group: '학과', subscriberCount: 559, adConsent: false },
  { id: 'dept:cf', label: { ko: '소비자학과' }, group: '학과', subscriberCount: 531, adConsent: false },
  { id: 'dept:mcce', label: { ko: '소재부품융합공학과' }, group: '학과', subscriberCount: 243, adConsent: false },
  { id: 'dept:sw-undergrad', label: { ko: '소프트웨어융합대학(학부생)' }, group: '학과', subscriberCount: 569, adConsent: false },
  { id: 'dept:sw-grad', label: { ko: '소프트웨어융합대학(대학원)' }, group: '학과', subscriberCount: 324, adConsent: false },
  { id: 'dept:cse-undergrad', label: { ko: '소프트웨어학과(학부생)' }, group: '학과', subscriberCount: 142, adConsent: false },
  { id: 'dept:cse-grad', label: { ko: '소프트웨어학과(대학원)' }, group: '학과', subscriberCount: 146, adConsent: false },
  { id: 'dept:math-undergrad', label: { ko: '수학과(학부생)' }, group: '학과', subscriberCount: 357, adConsent: false },
  { id: 'dept:math-grad', label: { ko: '수학과(대학원)' }, group: '학과', subscriberCount: 134, adConsent: false },
  { id: 'dept:mathedu', label: { ko: '수학교육과' }, group: '학과', subscriberCount: 526, adConsent: false },
  { id: 'dept:sport-undergrad', label: { ko: '스포츠과학대학(스포츠과학과)(학부생)' }, group: '학과', subscriberCount: 704, adConsent: false },
  { id: 'dept:sport-grad', label: { ko: '스포츠과학대학(스포츠과학과)(대학원)' }, group: '학과', subscriberCount: 272, adConsent: false },
  { id: 'dept:ie-undergrad', label: { ko: '시스템경영공학과(산업공학과)(학부생)' }, group: '학과', subscriberCount: 304, adConsent: false },
  { id: 'dept:ie-grad', label: { ko: '시스템경영공학과(산업공학과)(대학원)' }, group: '학과', subscriberCount: 133, adConsent: false },
  { id: 'dept:foodlife-undergrad', label: { ko: '식품생명공학과(학부생)' }, group: '학과', subscriberCount: 458, adConsent: false },
  { id: 'dept:foodlife-grad', label: { ko: '식품생명공학과(대학원)' }, group: '학과', subscriberCount: 510, adConsent: false },
  { id: 'dept:amse-undergrad', label: { ko: '신소재공학부(학부생)' }, group: '학과', subscriberCount: 289, adConsent: false },
  { id: 'dept:amse-grad', label: { ko: '신소재공학부(대학원)' }, group: '학과', subscriberCount: 307, adConsent: false },
  { id: 'dept:psych-undergrad', label: { ko: '심리학과(학부생)' }, group: '학과', subscriberCount: 83, adConsent: false },
  { id: 'dept:psych-grad', label: { ko: '심리학과(대학원)' }, group: '학과', subscriberCount: 441, adConsent: false },
  { id: 'dept:child-undergrad', label: { ko: '아동·청소년학과(학부생)' }, group: '학과', subscriberCount: 525, adConsent: false },
  { id: 'dept:child-grad', label: { ko: '아동·청소년학과(대학원)' }, group: '학과', subscriberCount: 263, adConsent: false },
  { id: 'dept:qie', label: { ko: '양자정보공학과' }, group: '학과', subscriberCount: 454, adConsent: false },
  { id: 'dept:energy', label: { ko: '에너지학과' }, group: '학과', subscriberCount: 875, adConsent: false },
  { id: 'dept:acting', label: { ko: '연기예술학과' }, group: '학과', subscriberCount: 255, adConsent: false },
  { id: 'dept:ftm-undergrad', label: { ko: '영상학과' }, group: '학과', subscriberCount: 297, adConsent: false },
  { id: 'dept:english-undergrad', label: { ko: '영어영문학과(학부생)' }, group: '학과', subscriberCount: 502, adConsent: false },
  { id: 'dept:english-grad', label: { ko: '영어영문학과(대학원)' }, group: '학과', subscriberCount: 260, adConsent: false },
  { id: 'dept:art-undergrad', label: { ko: '예술대학(학부생)' }, group: '학과', subscriberCount: 589, adConsent: false },
  { id: 'dept:art-grad', label: { ko: '예술대학(대학원)' }, group: '학과', subscriberCount: 846, adConsent: false },
  { id: 'dept:scos-undergrad', label: { ko: '유학대학(유학동양학과)(학부생)' }, group: '학과', subscriberCount: 410, adConsent: false },
  { id: 'dept:scos-grad', label: { ko: '유학대학(유학동양학과)(대학원)' }, group: '학과', subscriberCount: 580, adConsent: false },
  { id: 'dept:gene', label: { ko: '융합생명공학과' }, group: '학과', subscriberCount: 760, adConsent: false },
  { id: 'dept:aicon', label: { ko: '응용AI융합학부' }, group: '학과', subscriberCount: 117, adConsent: false },
  { id: 'dept:fashion-undergrad', label: { ko: '의상학과(학부생)' }, group: '학과', subscriberCount: 879, adConsent: false },
  { id: 'dept:fashion-grad', label: { ko: '의상학과(대학원)' }, group: '학과', subscriberCount: 419, adConsent: false },
  { id: 'dept:cscience-undergrad', label: { ko: '자연과학대학(학부생)' }, group: '학과', subscriberCount: 676, adConsent: false },
  { id: 'dept:cscience-grad', label: { ko: '자연과학대학(대학원)' }, group: '학과', subscriberCount: 544, adConsent: false },
  { id: 'dept:eee-undergrad', label: { ko: '전자전기공학부(학부생)' }, group: '학과', subscriberCount: 348, adConsent: false },
  { id: 'dept:eee-job', label: { ko: '전자전기공학부(취업)' }, group: '학과', subscriberCount: 312, adConsent: false },
  { id: 'dept:ice-undergrad', label: { ko: '정보통신대학(학부생)' }, group: '학과', subscriberCount: 662, adConsent: false },
  { id: 'dept:ice-grad', label: { ko: '정보통신대학(대학원)' }, group: '학과', subscriberCount: 491, adConsent: false },
  { id: 'dept:psd-undergrad', label: { ko: '정치외교학과(학부생)' }, group: '학과', subscriberCount: 341, adConsent: false },
  { id: 'dept:psd-grad', label: { ko: '정치외교학과(대학원)' }, group: '학과', subscriberCount: 600, adConsent: false },
  { id: 'dept:chinese-undergrad', label: { ko: '중어중문학과(학부생)' }, group: '학과', subscriberCount: 571, adConsent: false },
  { id: 'dept:chinese-grad', label: { ko: '중어중문학과(대학원)' }, group: '학과', subscriberCount: 897, adConsent: false },
  { id: 'dept:intelligentsw', label: { ko: '지능형소프트웨어학과' }, group: '학과', subscriberCount: 788, adConsent: false },
  { id: 'dept:ase', label: { ko: '차세대반도체공학연계전공' }, group: '학과', subscriberCount: 433, adConsent: false },
  { id: 'dept:philosophy-undergrad', label: { ko: '철학과(학부생)' }, group: '학과', subscriberCount: 239, adConsent: false },
  { id: 'dept:philosophy-grad', label: { ko: '철학과(대학원)' }, group: '학과', subscriberCount: 455, adConsent: false },
  { id: 'dept:comedu-undergrad', label: { ko: '컴퓨터교육과(학부생)' }, group: '학과', subscriberCount: 688, adConsent: false },
  { id: 'dept:comedu-grad', label: { ko: '컴퓨터교육과(대학원)' }, group: '학과', subscriberCount: 303, adConsent: false },
  { id: 'dept:quant', label: { ko: '퀀트응용경제학과' }, group: '학과', subscriberCount: 268, adConsent: false },
  { id: 'dept:stat-undergrad', label: { ko: '통계학과(학부생)' }, group: '학과', subscriberCount: 223, adConsent: false },
  { id: 'dept:stat-grad', label: { ko: '통계학과(대학원)' }, group: '학과', subscriberCount: 718, adConsent: false },
  { id: 'dept:french-undergrad', label: { ko: '프랑스어문학과(학부생)' }, group: '학과', subscriberCount: 693, adConsent: false },
  { id: 'dept:french-grad', label: { ko: '프랑스어문학과(대학원)' }, group: '학과', subscriberCount: 446, adConsent: false },
  { id: 'dept:hakbu', label: { ko: '학부대학(계열제)' }, group: '학과', subscriberCount: 673, adConsent: false },
  { id: 'dept:klccedu', label: { ko: '한문교육과' }, group: '학과', subscriberCount: 214, adConsent: false },
  { id: 'dept:klcc-undergrad', label: { ko: '한문학과(학부생)' }, group: '학과', subscriberCount: 756, adConsent: false },
  { id: 'dept:klcc-grad', label: { ko: '한문학과(대학원)' }, group: '학과', subscriberCount: 47, adConsent: false },
  { id: 'dept:gsg', label: { ko: '행정학과(국정전문대학원)' }, group: '학과', subscriberCount: 891, adConsent: false },
  { id: 'dept:chem', label: { ko: '화학과' }, group: '학과', subscriberCount: 143, adConsent: false },
  { id: 'dept:cheme', label: { ko: '화학공학과' }, group: '학과', subscriberCount: 544, adConsent: false },
  { id: 'dept:medicine', label: { ko: '의과대학' }, group: '학과', subscriberCount: 861, adConsent: false },
  { id: 'dept:cal-undergrad', label: { ko: '건설환경공학부(학부)' }, group: '학과', subscriberCount: 796, adConsent: false },
  { id: 'dept:cal-grad', label: { ko: '건설환경공학부(대학원)' }, group: '학과', subscriberCount: 589, adConsent: false },
  { id: 'dept:bio-undergrad', label: { ko: '생명과학과(학부)' }, group: '학과', subscriberCount: 894, adConsent: false },
  { id: 'dept:bio-grad', label: { ko: '생명과학과(대학원)' }, group: '학과', subscriberCount: 693, adConsent: false },
  { id: 'dept:pharm', label: { ko: '약학대학' }, group: '학과', subscriberCount: 266, adConsent: false },
  { id: 'dept:nano', label: { ko: '나노공학과' }, group: '학과', subscriberCount: 143, adConsent: false },
  { id: 'dept:gsc', label: { ko: '중국대학원' }, group: '학과', subscriberCount: 887, adConsent: false },
  { id: 'library:lib-hssc', label: { ko: '중앙학술정보관' }, group: '도서관', subscriberCount: 480, adConsent: false },
  { id: 'library:lib-nsc', label: { ko: '삼성학술정보관' }, group: '도서관', subscriberCount: 792, adConsent: false },
  { id: 'library:lib-all', label: { ko: '학술정보관 본부' }, group: '도서관', subscriberCount: 481, adConsent: false },
  { id: 'dorm:dorm-hssc', label: { ko: '명륜학사 (인사캠 기숙사)' }, group: '기숙사', subscriberCount: 389, adConsent: false },
  { id: 'dorm:dorm-nsc', label: { ko: '봉룡학사 (자과캠 기숙사)' }, group: '기숙사', subscriberCount: 79, adConsent: false },
  { id: 'general:health', label: { ko: '건강센터' }, group: '일반', subscriberCount: 435, adConsent: false },
  { id: 'general:ccrf', label: { ko: '공동기기원' }, group: '일반', subscriberCount: 159, adConsent: false },
  { id: 'general:saint', label: { ko: '나노과학기술원' }, group: '일반', subscriberCount: 708, adConsent: false },
  { id: 'general:skku-notice03', label: { ko: '성균관대_통합(입학)' }, group: '일반', subscriberCount: 762, adConsent: false },
  { id: 'general:skku-notice08', label: { ko: '성균관대_통합(일반)' }, group: '일반', subscriberCount: 767, adConsent: false },
  { id: 'general:chec', label: { ko: '성균인성교육센터' }, group: '일반', subscriberCount: 133, adConsent: false },
  { id: 'general:larc', label: { ko: '실험동물센터' }, group: '일반', subscriberCount: 853, adConsent: false },
  { id: 'general:helper', label: { ko: '인권센터' }, group: '일반', subscriberCount: 535, adConsent: false },
  { id: 'general:support', label: { ko: '장애학생지원센터' }, group: '일반', subscriberCount: 278, adConsent: false },
  { id: 'general:scc', label: { ko: '카운슬링센터' }, group: '일반', subscriberCount: 418, adConsent: false },
  { id: 'general:success', label: { ko: '학생성공센터' }, group: '일반', subscriberCount: 32, adConsent: false },
];
